# Generated by Django 4.2.27 on 2026-01-20 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donation_is_archived'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to='donations.donation'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('GENERAL', 'Général'), ('APPOINTMENT', 'Rendez-vous'), ('DONATION_ISSUE', 'Problème de Don'), ('SUPPORT', 'Support')], default='GENERAL', max_length=20, verbose_name='Type de message'),
        ),
    ]
