# Generated by Django 4.2.27 on 2026-01-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(default='cyprusforchrist@gmail.com', max_length=254, verbose_name='Email'),
        ),
    ]
