# Generated by Django 4.2.27 on 2026-01-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archivé (supprimé logiquement)'),
        ),
    ]
