# Generated by Django 4.2.27 on 2026-01-20 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('PLANNED', 'Planifié'), ('LIVE', 'En Direct'), ('ENDED', 'Terminé')], default='PLANNED', max_length=20)),
                ('stream_key', models.CharField(blank=True, max_length=255, verbose_name='Clé de Flux')),
                ('playback_url', models.CharField(blank=True, max_length=512, verbose_name='URL de Lecture')),
                ('ingest_endpoint', models.CharField(blank=True, max_length=512, verbose_name="Point d'entrée (RTMP)")),
                ('scheduled_start', models.DateTimeField(blank=True, null=True, verbose_name='Début prévu')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Lancé à')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé à')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flux Live',
                'verbose_name_plural': 'Flux Lives',
                'ordering': ['-created_at'],
            },
        ),
    ]
