# Generated by Django 4.2.27 on 2026-01-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0004_alter_sermon_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='category',
            field=models.CharField(choices=[('SUNDAY_SERVICE', 'Culte Dimanche'), ('PREACHING', 'Prédication'), ('TEACHING', 'Enseignement'), ('EXHORTATION', 'Exhortation'), ('MEDITATION', 'Méditation'), ('BIBLE_STUDY', 'Étude Biblique'), ('YOUTH', 'Jeunesse'), ('CONFERENCE', 'Conférence'), ('WORSHIP', 'Louange'), ('OTHER', 'Autre')], default='SUNDAY_SERVICE', max_length=20, verbose_name='Catégorie'),
        ),
    ]
